version: "3.9"

services:
  # -------------------------------
  # PostgreSQL Database
  # -------------------------------
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: huly_gitlab_sync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -------------------------------
  # FastAPI Sync Engine
  # -------------------------------
  app:
    build: .
    container_name: huly-sync-app
    restart: always
    ports:
      - "3000:3000"

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql://mars:supersecret@db:5432/huly_gitlab_sync

      GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
      GITLAB_BASE_URL: ${GITLAB_BASE_URL}
      GITLAB_DEFAULT_PROJECT_ID: ${GITLAB_DEFAULT_PROJECT_ID}
      ENABLE_HULY_POLLER: ${ENABLE_HULY_POLLER}
      HULY_PROJECT_ID: ${HULY_PROJECT_ID}
      HULY_POLL_INTERVAL_SECONDS: 10

      # FastAPI communicates with the adapter
      HULY_ADAPTER_URL: http://huly-adapter:3001

    depends_on:
      - db
      - huly-adapter

  # -------------------------------
  # Huly Adapter (Node + TypeScript)
  # -------------------------------
  huly-adapter:
    build:
      context: ./huly-adapter

    container_name: huly-adapter

    restart: always

    ports:
      - "3001:3001"

    volumes:
      - ./huly-adapter:/app
      - /app/node_modules

    environment:
      HULY_URL: ${HULY_URL}
      HULY_TOKEN: ${HULY_API_TOKEN}
      HULY_WORKSPACE_ID: ${HULY_WORKSPACE_ID}
      HULY_PROJECT_ID: ${HULY_PROJECT_ID}
      ENABLE_HULY_POLLER: ${ENABLE_HULY_POLLER}
      HULY_POLL_INTERVAL_SECONDS: 10
      

volumes:
  postgres_data: