"""create initial tables

Revision ID: 26ecdfbb3801
Revises: 
Create Date: 2026-07-09 15:02:40.938237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ecdfbb3801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_project_id', sa.BigInteger(), nullable=False),
    sa.Column('gitlab_project_name', sa.String(), nullable=True),
    sa.Column('gitlab_issue_id', sa.BigInteger(), nullable=False),
    sa.Column('gitlab_issue_iid', sa.BigInteger(), nullable=True),
    sa.Column('gitlab_issue_url', sa.Text(), nullable=True),
    sa.Column('gitlab_title', sa.Text(), nullable=True),
    sa.Column('huly_project_id', sa.String(), nullable=False),
    sa.Column('huly_issue_id', sa.String(), nullable=False),
    sa.Column('huly_identifier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gitlab_project_id', 'gitlab_issue_id', name='uq_gitlab_issue_mapping')
    )
    op.create_index(op.f('ix_issue_mapping_id'), 'issue_mapping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_mapping_id'), table_name='issue_mapping')
    op.drop_table('issue_mapping')
    # ### end Alembic commands ###
