"""Create initial tables

Revision ID: 881eaeb0b5a2
Revises: 
Create Date: 2026-06-30 15:31:26.709891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881eaeb0b5a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_comment_id', sa.String(), nullable=False),
    sa.Column('huly_comment_id', sa.String(), nullable=False),
    sa.Column('issue_mapping_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_mapping_gitlab_comment_id'), 'comment_mapping', ['gitlab_comment_id'], unique=True)
    op.create_index(op.f('ix_comment_mapping_huly_comment_id'), 'comment_mapping', ['huly_comment_id'], unique=True)
    op.create_index(op.f('ix_comment_mapping_id'), 'comment_mapping', ['id'], unique=False)
    op.create_table('issue_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_issue_id', sa.String(), nullable=False),
    sa.Column('huly_issue_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_mapping_gitlab_issue_id'), 'issue_mapping', ['gitlab_issue_id'], unique=True)
    op.create_index(op.f('ix_issue_mapping_huly_issue_id'), 'issue_mapping', ['huly_issue_id'], unique=True)
    op.create_index(op.f('ix_issue_mapping_id'), 'issue_mapping', ['id'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_id'), 'sync_log', ['id'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_state_id'), 'sync_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_state_id'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_sync_log_id'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_issue_mapping_id'), table_name='issue_mapping')
    op.drop_index(op.f('ix_issue_mapping_huly_issue_id'), table_name='issue_mapping')
    op.drop_index(op.f('ix_issue_mapping_gitlab_issue_id'), table_name='issue_mapping')
    op.drop_table('issue_mapping')
    op.drop_index(op.f('ix_comment_mapping_id'), table_name='comment_mapping')
    op.drop_index(op.f('ix_comment_mapping_huly_comment_id'), table_name='comment_mapping')
    op.drop_index(op.f('ix_comment_mapping_gitlab_comment_id'), table_name='comment_mapping')
    op.drop_table('comment_mapping')
    # ### end Alembic commands ###
